### ISSUE TITLE
Installing FES2014 with conda, Looking for incompatible packages

### ISSUE THREAD

**Issue by G4occhi** [CNES/aviso-fes#19]
Hi, I would like to migrate to FES2014 and I am trying to install it with conda on my system.

Unfortunately the command:
conda install pyfes -c fbriol

GIVE:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                              

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31

Honestly, I have no Idea about the issue. 
May you suggest any solutions?

I have also tried cmake with no success since make -j give the following:
fatal error: uthash.h: No such file or director

Thanks
Giova

**Comment by ludwigus** [comment]
Hi,
I have exactly the same problems installing pyfes on Ubuntu22.04. Conda gives the reported error (just with glibc==2.35 instead). 
In order to build the library myself I needed to install the uthash libs manually (`sudo apt install uthash-dev`). After that, building and installing with the default options (as given in the install instructions) works. However, if I try build to the python lib as well ( `-DBUILD_PYTHON=ON`) I get the following output:
```
$ cmake .. -DCMAKE_INSTALL_PREFIX=/opt/local -DBUILD_PYTHON=ON
-- FES version: 2.9.4
-- Build type: RELWITHDEBINFO
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- Found Python3: /usr/bin/python3.10 (found version "3.10.6") found components: Interpreter Development Development.Module Development.Embed 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so (found version "3.10.6") 
CMake Error at CMakeLists.txt:192 (add_subdirectory):
  The source directory

    /home/username/tmp/test_tide/aviso-fes-2.9.4/third_party/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at python/CMakeLists.txt:16 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "/home/username/tmp/test_tide/aviso-fes-2.9.4/build/CMakeFiles/CMakeOutput.log".
See also "/home/username/tmp/test_tide/aviso-fes-2.9.4/build/CMakeFiles/CMakeError.log".
```
I have attached the two files but I couldn't find anything there that helped me solve the problem.
[CMakeError.log](https://github.com/CNES/aviso-fes/files/11661885/CMakeError.log)
[CMakeOutput.log](https://github.com/CNES/aviso-fes/files/11661886/CMakeOutput.log)
Is this a bug or did I do something wrong?

**Comment by njuMarineGeoscience** [comment]
I also have nearly the same problem. I got the error when trying to install via conda:

Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyfes

Current channels:
  - https://conda.anaconda.org/fbriol/osx-arm64
  - https://conda.anaconda.org/fbriol/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

I used conda search pyfes, but only found pyfesom

**Comment by datpthus** [comment]
Hi, I followed hints from this: https://github.com/kvos/CoastSat.slope/issues/21
"So, the answer was pretty easy, here is the answer from the FES14 issue:
Try to update your conda environment (conda update --all -c conda-forge) then reinstall the library (conda install pyfes -c fbriol -c conda-forge)

This did the trick. By the way, the latest FES version runs on python 3.9"
by Alerovere
 and I created a new env using python 3.9 or newer and then I upgraded to latest Conda. That works for me. You should try that! 

@njuMarineGeoscience @G4occhi @ludwigus

**Comment by njuMarineGeoscience** [comment]
> conda update --all -c conda-forge

Thank you @datpthus , I tried this but still got the same error

**Comment by njuMarineGeoscience** [comment]
I did not find pyfes or fbriol in my anaconda navigator, is it the problem?

**Comment by datpthus** [comment]
@njuMarineGeoscience hi, what I did is pretty simple: 
- I remove current conda version from my computer and re-install the latest conda version 
- I create a new env (e.g. fesenv) using python 3.9 or above ( I tested with python 3.10 is OK). And then I run conda install pyfes -c fbriol -c conda-forge. That worked for me. 

I know others also found difficult to install FES2014 but perharps I was lucky. However, could you try that?

**Comment by datpthus** [comment]
@njuMarineGeoscience : for the latest Conda version 2.4.2 I can find pyfes package (2.9.4) from Anaconda Navigator. So, I really think that you should re-install Conda.

**Comment by njuMarineGeoscience** [comment]
@datpthus Thank you! I think maybe pyfes does not support the MAC M1 chip. The file size of the anaconda installation package for the M1 was quite a bit smaller than for Intel, that's why I did not find pyfes. I just tried to download the intel version on my M1 MAC, and it worked! I don't understand, but now I have pyfes installed.

**Comment by datpthus** [comment]
@njuMarineGeoscience thats great!

**Comment by xxxzzz32** [comment]
Hello everyone! I am writing this comment to sum up my experience about installing fes2014, and I hope my experience can help people who have difficulties installing pyfes. 
First of all, my computer system is Windows 11, the version of Anaconda is 2023.07-2, and the version of python in 'base' environment is 3.11.4.

The first try is in the 'base' environment. I typed 'conda update --all -c conda-forge' just as @datpthus said. Here, you'd better run Anaconda Prompt as administrator. About one hour later, it displayed:
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Maybe you will cost fewer time in this step, because my download speed is slow. And then I typed 'conda install pyfes -c fbriol'. After a long wait , it ddisplayed:
Specifications:
  - pyfes -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']
Your python: python=3.11
So I thought maybe pyfes was not compatible with python 3.11. In this website 'https://anaconda.org/fbriol/pyfes/files', I found the latest version of pyfes was named 'pyfes-2.9.5-py310h2e52968_0.tar.bz2', so I confirmed that I should try in python 3.10.

In the second try, I runned Anaconda Prompt as administrator, and typed 'conda create python310 python=3.10' to create a new environment. Then I typed 'conda update --all -c conda-forge', and it displayed as above. Lastly, I typed 'conda install pyfes -c fbriol', and it displayed:
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
To confirm pyfes is installed, I typed 'conda list', and I found pyfes 2.9.4 inside. 

Thank you to the seniors for your valuable experience!

**Comment by xiyang712** [comment]
@xxxzzzz32
Hello, I should have installed successfully, but when I run the program I get this error.
![image](https://github.com/CNES/aviso-fes/assets/115886880/d1dd2bbf-bbde-4671-87e0-e2a9bda7f8a2)
![image](https://github.com/CNES/aviso-fes/assets/115886880/03d8c7dd-2997-4dd4-beed-db0a340d757c)

**Comment by xxxzzz32** [comment]
I guess that you installed sucessfully in cmd or anaconda prompt, but you get this error in jupyter notebook. Therefore, maybe the environmnt in jupyter doesn't have installed pyfes. Maybe you should change the environment in jupyter.



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/30/2023 14:14 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [CNES/aviso-fes] Installing FES2014 with conda, Looking for incompatible packages (Issue #19) |

@xxxzzzz32
Hello, I should have installed successfully, but when I run the program I get this error.

**Comment by fbriol** [comment]
This question is out of date. Please use the most recent version of this software. You can install it from [Conda](https://cnes.github.io/aviso-fes/conda.html).
