### ISSUE TITLE
module 'pyfes' has no attribute 'Handler'

### ISSUE THREAD

**Issue by Phuongtran75** [CNES/aviso-fes#32]
Hi,

I downloaded the new version of aviso-fes but I still get error.

AttributeError                            Traceback (most recent call last)
Cell In[10], line 7
      5 config_ocean = os.path.join(filepath, 'ocean_tide.yaml') # change to ocean_tide.ini
      6 config_load =  os.path.join(filepath, 'load_tide.yaml')  # change to load_tide.ini
----> 7 ocean_tide = pyfes.Handler("ocean", "io", config_ocean)
      8 load_tide = pyfes.Handler("radial", "io", config_load)
     10 # coordinates of the location (always select a point 1-2km offshore from the beach)
     11 # if the model returns NaNs, change the location of your point further offshore.

AttributeError: module 'pyfes' has no attribute 'Handler'

Can you give me idea to solve it?

THank you

**Comment by fbriol** [comment]
Hi,

Thank you for reaching out. The error you're encountering (`AttributeError: module 'pyfes' has no attribute 'Handler'`) is likely because you're attempting to use the legacy [version](https://github.com/CNES/aviso-fes/releases) (2.9.7) of the pyfes library with the new one (2024.6.0). The latest version of the library introduces significant changes that are not backward compatible with the old one.

To resolve this issue, you'll need to follow the updated documentation for the new version of aviso-fes. Please ensure you have the latest version installed and refer to the example code for predictions provided in the documentation.

You can find the updated documentation here: [Aviso-FES Documentation](https://cnes.github.io/aviso-fes/)

Specifically, check out the example of the new code for predictions: [New Code Prediction Example](https://cnes.github.io/aviso-fes/auto_examples/ex_prediction.html)

This should guide you through the necessary changes to your code and configuration files.
